version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=book
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=book
    ports:
      - 5432:5432
  web:
    build: ""
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db


volumes:
  postgres_data:
