# Generated by Django 3.2.5 on 2021-11-06 16:41

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('AUTHOR', 'Автор'), ('READER', 'Читатель')], default='READER', max_length=10, verbose_name='Тип пользователя')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=(main.models.UserMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.users', verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
